plugins {
    alias(libs.plugins.semver)
    id 'jacoco'
    id 'signing'
    id 'maven-publish'
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
}

semver {
    tagPrefix.set("crime-commons-classes-")
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

bootJar {
    enabled = false
}

jar {
    enabled = true
}

dependencies {

    // ---- Monitoring & Logging ----
    implementation 'io.micrometer:micrometer-tracing'

    // ---- Jackson ----
    implementation platform(libs.jackson.bom)
    implementation libs.jackson.core
    implementation libs.jackson.databind
    implementation libs.jackson.annotations

    // ---- Core Module ----
    implementation "org.apache.commons:commons-lang3"
    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation "org.springframework.boot:spring-boot-starter-test"
    implementation libs.swagger.annotations
    implementation libs.jakarta.validation.api
    implementation libs.commons.io

    // ---- Annotations ----
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
}

publishing {
    publications {
        maven(MavenPublication) {

            from components.java

            pom {
                artifactId = project.name
                name = "Crime Apps Common Classes"
                url = "https://github.com/ministryofjustice/laa-crime-commons"
                description = "A Spring Boot auto-configuration library with all common classes"

                licenses {
                    license {
                        name = "MIT"
                        url = "https://opensource.org/licenses/MIT"
                    }
                }
                organization {
                    name = "Justice Digital"
                }
                developers {
                    developer {
                        id = "mhowell494"
                        name = "Matthew Howell"
                        email = "matthew.howell@digital.justice.gov.uk"
                    }
                }
                scm {
                    url = "https://github.com/ministryofjustice/laa-crime-commons.git"
                }
            }
        }
    }
}

signing {
    sign publishing.publications.maven
    def signingKey = findProperty("signingKey")
    def signingPassword = findProperty("signingPassword")
    useInMemoryPgpKeys(signingKey, signingPassword)
}

test {
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        csv.required = false
        html.required = false
    }
}

tasks.named("test") {
    useJUnitPlatform()
}


